################################################################################
#                                                                              #
#   Copyright 2024 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

name: Check the Package Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    branches:
      - main
      - develop
      - release/**
      
jobs:

  check-linux-actions:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Run 'package/appimage/setup-appimagetool' action
      id: setup-appimagetool
      uses: ./package/appimage/setup-appimagetool
      with:
        appimagetool-runtime: 'all'

    - name: Test 'package/appimage/setup-appimagetool' action
      shell: bash
      run: |

        if ( ! command -v "${{ env.GITHUB_ACTION_APPIMAGETOOL_FILE }}" ); then
          echo "::error::'package/appimage/setup-appimagetool' test failed. env.GITHUB_ACTION_APPIMAGETOOL_FILE is '${{ env.GITHUB_ACTION_APPIMAGETOOL_FILE }}'. The command not found"
          exit 1
        elif [ ! -d "${{ env.GITHUB_ACTION_APPIMAGETOOL_DIR }}" ]; then
          echo "::error::'package/appimage/setup-appimagetool' test failed. env.GITHUB_ACTION_APPIMAGETOOL_DIR is '${{ env.GITHUB_ACTION_APPIMAGETOOL_DIR }}'. The directory does not exist"
          exit 2
        else
          echo "::notice::'package/appimage/setup-appimagetool' test passed."
        fi
