################################################################################
#                                                                              #
#   Copyright 2023 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

name: Check Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Run version-number action
      id: version-number
      uses: finebits/github-actions/version-number@main

    - name: Check version-number action
      run: | 
        echo "Short version: ${{ steps.version-number.outputs.short-version }}"
        echo "Full version: ${{ steps.version-number.outputs.full-version }}"
        echo "Semantic version: ${{ steps.version-number.outputs.semantic-version }}"
        echo "Major: ${{ steps.version-number.outputs.major }}"
        echo "Minor: ${{ steps.version-number.outputs.minor }}"
        echo "Patch: ${{ steps.version-number.outputs.patch }}"
        echo "Build: ${{ steps.version-number.outputs.build }}"
        echo "Attempt: ${{ steps.version-number.outputs.attempt }}"
        echo "Today: ${{ steps.version-number.outputs.today }}"
        echo "Revision: ${{ steps.version-number.outputs.revision }}"
        echo "Suffix: ${{ steps.version-number.outputs.suffix }}"
