################################################################################
#                                                                              #
#   Copyright 2024 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

name: Test Package Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    branches:
      - main
      - develop
      - release/**
      
jobs:

  test-linux-actions:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Run 'package/appimage/setup-appimagetool' action
      id: setup-appimagetool
      uses: ./package/appimage/setup-appimagetool
      with:
        appimagetool-runtime: 'all'

    - name: Test 'package/appimage/setup-appimagetool' action
      shell: bash
      run: |

        if ( ! command -v "${{ env.APPIMAGETOOL_FILE }}" ); then
          echo "::error::'package/appimage/setup-appimagetool' test failed. env.APPIMAGETOOL_FILE is '${{ env.APPIMAGETOOL_FILE }}' command not found"
          exit 1
        else
          echo "::notice::'package/appimage/setup-appimagetool' test passed."
        fi

    - name: Prepare-Run 'package/appimage/pack' action  
      shell: bash
      run: |
        bash "./package/appimage/.test/prepare-Test.AppDir.sh"

    - name: Run './package/appimage/pack' action
      id: pack-appimage
      uses: ./package/appimage/pack
      with:
        package-runtime: 'aarch64'
        package-output-dir: './.output/aarch64'
        package-app-dir: './package/appimage/.test/Test.AppDir'

    - name: Run './package/appimage/pack' action
      id: pack-appimage
      uses: ./package/appimage/pack
      with:
        package-runtime: 'x86_64'
        package-output-dir: './.output/x86_64'
        package-app-dir: './package/appimage/.test/Test.AppDir'

    - name: Test './package/appimage/pack' action
      shell: bash
      run: |
        package=${{ steps.pack-appimage.outputs.package }}

        result=$("$package")
        if [ "$result" != "Hello AppImage" ]; then
          echo "::error::'package/appimage/pack' test failed. The package '$package' is packed incorrect"
          exit 2
        else
          echo "::notice::'package/appimage/pack' test passed."
        fi

    - name: Print bash environment values
      shell: bash
      run: printenv

    - name: Print powershell environment values
      shell: pwsh
      run: Get-ChildItem "env:"
